version: "3.9"

services:
  emilia:
    build: .
    image: emilia:${TAG}
    container_name: emilia
    network_mode: host # or bridge or whatever your network is
    pull_policy: never
  restarter:
    image: docker:cli
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    command: ["/bin/sh", "-c", "while true; do sleep 43200; docker restart emilia; done"] # restart every 12 hours
    restart: unless-stopped
    network_mode: host

networks:
  default: 
    external: true
    name: host
